"use client";

import React, { useState, Suspense } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import BookCard from "@/components/BookCard";
import { api } from "@/utils/api";
import { toast } from "sonner";
import { useAuthStore } from "@/store/useAuthStore";
import {
  Search,
  Compass,
  BookOpen,
  Import,
  Sparkles,
  X,
  ChevronLeft,
  ChevronRight,
  Loader2,
} from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

function SearchResultsContent() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const queryClient = useQueryClient();
  const query = searchParams.get("q") || "";
  const { isAuthenticated } = useAuthStore();

  // E-Book Reader States
  const [readerOpen, setReaderOpen] = useState(false);
  const [digitalBook, setDigitalBook] = useState<any>(null);
  const [readingBookTitle, setReadingBookTitle] = useState("");
  const [currentChapterIndex, setCurrentChapterIndex] = useState(0);
  const [readerFont, setReaderFont] = useState<"serif" | "sans">("serif");
  const [readerSize, setReaderSize] = useState<"sm" | "md" | "lg">("md");
  const [readerTheme, setReaderTheme] = useState<"sepia" | "dark" | "light">("sepia");
  const [loadingBookId, setLoadingBookId] = useState<string | null>(null);

  // 1. Unified Search query
  const { data: searchRes, isLoading } = useQuery({
    queryKey: ["searchQuery", query],
    queryFn: async () => {
      const res = await api.get("/search", { params: { q: query } });
      return res.data;
    },
    enabled: !!query,
  });

  const localBooks = searchRes?.localBooks || [];
  const externalBooks = searchRes?.externalBooks || [];

  // 2. Import External Book Mutation
  const importMutation = useMutation({
    mutationFn: async (extBook: any) => {
      const res = await api.post("/books", {
        title: extBook.title,
        description: extBook.description || "No description available.",
        thumbnail: extBook.thumbnail || undefined,
        pages: extBook.pages || undefined,
        publishedYear: extBook.publishedYear || undefined,
        authors: extBook.authors,
        categories: extBook.categories,
      });
      return res.data;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ["searchQuery", query] });
      toast.success(`Successfully imported: "${data.book.title}" to catalog!`);
      // Redirect to newly created book detail page
      router.push(`/books/${data.book.id}`);
    },
    onError: (err: any) => {
      toast.error(err.response?.data?.message || "Failed to import book");
    },
  });

  const handleImportBook = (extBook: any) => {
    if (!isAuthenticated) {
      toast.error("Please log in to import books to the catalog.");
      return;
    }
    toast.info(`Importing "${extBook.title}"...`);
    importMutation.mutate(extBook);
  };

  // 3. Direct AI E-Book Generation & Launch
  const handleReadBook = async (extBook: any) => {
    if (!isAuthenticated) {
      toast.error("Please log in to read digital books.");
      return;
    }

    const uniqueId = extBook.id || extBook.title;
    setLoadingBookId(uniqueId);
    toast.info(`Initializing AI E-Book for "${extBook.title}"...`);

    try {
      // Step A: Import/Create the book in local catalog in background
      const res = await api.post("/books", {
        title: extBook.title,
        description: extBook.description || "No description available.",
        thumbnail: extBook.thumbnail || undefined,
        pages: extBook.pages || undefined,
        publishedYear: extBook.publishedYear || undefined,
        authors: extBook.authors,
        categories: extBook.categories,
      });
      const bookId = res.data.book.id;

      // Step B: Generate the DeepSeek E-Book chapters
      const dbRes = await api.post(`/books/${bookId}/digital-book`);
      
      // Step C: Set reader states and launch modal
      setDigitalBook(dbRes.data.digitalBook);
      setReadingBookTitle(extBook.title);
      setCurrentChapterIndex(0);
      setReaderOpen(true);

      toast.success(
        dbRes.data.source === "gemini_ai" // (Backend is proxied to DeepSeek but labels source AI)
          ? "Digital book generated by DeepSeek AI!"
          : "Loaded digital book chapters from cache."
      );
    } catch (err: any) {
      toast.error(err.response?.data?.message || "Could not generate digital book content.");
    } finally {
      setLoadingBookId(null);
    }
  };

  if (!query) {
    return (
      <div className="flex flex-col items-center justify-center py-20 border rounded-2xl bg-white dark:bg-gray-950/20">
        <Search className="h-16 w-16 text-gray-300 dark:text-gray-700 mb-4" />
        <h3 className="text-lg font-bold">Search BookHub</h3>
        <p className="text-sm text-gray-500 dark:text-gray-400 mt-1 max-w-sm text-center">
          Enter a book title or author query in the search bar above to begin.
        </p>
      </div>
    );
  }

  if (isLoading) {
    return <p className="animate-pulse text-center font-semibold py-12">Querying database & Google Books API...</p>;
  }

  return (
    <div className="space-y-10">
      {/* Search Header Info */}
      <div>
        <h1 className="text-2xl font-bold">Search Results</h1>
        <p className="text-sm text-gray-500">
          Showing matching titles for query: &ldquo;<span className="font-semibold text-primary">{query}</span>&rdquo;
        </p>
      </div>

      {/* Local Books results */}
      <div className="space-y-4">
        <h3 className="text-lg font-bold border-b pb-2 flex items-center gap-2">
          <BookOpen className="h-5 w-5 text-primary" />
          Catalog Matches ({localBooks.length})
        </h3>
        {localBooks.length === 0 ? (
          <p className="text-xs text-gray-400">No matching books found in our local database catalog.</p>
        ) : (
          <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-5 gap-6">
            {localBooks.map((book: any) => (
              <BookCard key={book.id} book={book} />
            ))}
          </div>
        )}
      </div>

      {/* Google Books results */}
      <div className="space-y-4 pt-4">
        <h3 className="text-lg font-bold border-b pb-2 flex items-center gap-2">
          <Compass className="h-5 w-5 text-indigo-600" />
          Google Books Results ({externalBooks.length})
        </h3>
        {externalBooks.length === 0 ? (
          <p className="text-xs text-gray-400">No results found on Google Books.</p>
        ) : (
          <div className="grid md:grid-cols-2 gap-4">
            {externalBooks.map((ext: any) => {
              const uniqueId = ext.id || ext.title;
              const isCurrentLoading = loadingBookId === uniqueId;
              
              return (
                <div
                  key={ext.id}
                  className="border p-4 rounded-2xl bg-white dark:bg-gray-900 shadow-sm flex justify-between gap-4 items-center glow-card"
                >
                  <div className="flex gap-4 items-center min-w-0">
                    {ext.thumbnail ? (
                      <img src={ext.thumbnail} alt={ext.title} className="h-16 w-11 object-cover rounded-lg flex-shrink-0" />
                    ) : (
                      <div className="h-16 w-11 bg-gray-100 dark:bg-gray-800 rounded-lg flex items-center justify-center text-gray-400 flex-shrink-0">
                        <Search className="h-4 w-4" />
                      </div>
                    )}
                    <div className="min-w-0">
                      <h4 className="font-bold text-sm truncate">{ext.title}</h4>
                      <p className="text-xs text-gray-400 truncate">by {ext.authors.join(", ")}</p>
                      <span className="inline-block mt-1 text-[10px] bg-gray-100 dark:bg-gray-800 px-2 py-0.5 rounded text-gray-500 font-semibold">
                        {ext.categories[0]}
                      </span>
                    </div>
                  </div>

                  <div className="flex flex-col sm:flex-row gap-2 flex-shrink-0">
                    {/* Import Button */}
                    <button
                      onClick={() => handleImportBook(ext)}
                      disabled={importMutation.isPending || loadingBookId !== null}
                      className="inline-flex items-center gap-1 bg-indigo-500/10 hover:bg-indigo-500/20 text-indigo-600 dark:text-indigo-400 px-3 py-2 rounded-xl text-xs font-bold transition-all cursor-pointer disabled:opacity-50"
                    >
                      <Import className="h-3.5 w-3.5" /> Import Catalog
                    </button>

                    {/* AI E-Book Reader Trigger */}
                    <button
                      onClick={() => handleReadBook(ext)}
                      disabled={loadingBookId !== null || importMutation.isPending}
                      className="inline-flex items-center gap-1.5 bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-700 hover:to-indigo-700 text-white px-3.5 py-2 rounded-xl text-xs font-bold transition-all shadow-sm hover:scale-[1.02] cursor-pointer disabled:opacity-50 disabled:pointer-events-none"
                    >
                      {isCurrentLoading ? (
                        <>
                          <Loader2 className="h-3.5 w-3.5 animate-spin" />
                          Reading...
                        </>
                      ) : (
                        <>
                          <BookOpen className="h-3.5 w-3.5" />
                          Read E-Book
                        </>
                      )}
                    </button>
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>

      {/* AI Digital Book Reader Modal */}
      <AnimatePresence>
        {readerOpen && digitalBook && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black/70 backdrop-blur-sm z-50 flex items-center justify-center p-4 sm:p-6 select-none"
          >
            <motion.div
              initial={{ scale: 0.95, y: 20 }}
              animate={{ scale: 1, y: 0 }}
              exit={{ scale: 0.95, y: 20 }}
              className={`w-full max-w-6xl h-[85vh] flex flex-col overflow-hidden rounded-3xl shadow-2xl border transition-all duration-300 ${
                readerTheme === "sepia"
                  ? "bg-[#fbf6eb] text-[#433422] border-[#ebdcb9]"
                  : readerTheme === "dark"
                  ? "bg-[#121212] text-[#e0e0e0] border-[#2d2d2d]"
                  : "bg-white text-gray-900 border-gray-200"
              }`}
            >
              {/* Header */}
              <div className={`flex items-center justify-between px-6 py-4 border-b ${
                readerTheme === "sepia"
                  ? "border-[#ebdcb9]"
                  : readerTheme === "dark"
                  ? "border-[#2d2d2d]"
                  : "border-gray-200"
              }`}>
                <div className="min-w-0">
                  <h3 className="font-bold text-xs uppercase tracking-wider opacity-60">AI Digital Reader</h3>
                  <h2 className="font-black text-lg truncate">{readingBookTitle}</h2>
                </div>

                {/* Reader Options */}
                <div className="flex items-center gap-4">
                  {/* Font Controls */}
                  <div className="hidden sm:flex items-center border rounded-xl overflow-hidden p-0.5 border-current/25">
                    <button
                      onClick={() => setReaderFont("serif")}
                      className={`px-2.5 py-1 text-xs font-serif font-semibold rounded-lg ${
                        readerFont === "serif" ? "bg-primary text-white" : "hover:bg-current/5 text-current/80"
                      }`}
                    >
                      Serif
                    </button>
                    <button
                      onClick={() => setReaderFont("sans")}
                      className={`px-2.5 py-1 text-xs font-sans font-semibold rounded-lg ${
                        readerFont === "sans" ? "bg-primary text-white" : "hover:bg-current/5 text-current/80"
                      }`}
                    >
                      Sans
                    </button>
                  </div>

                  {/* Text Size Controls */}
                  <div className="hidden sm:flex items-center border rounded-xl overflow-hidden p-0.5 border-current/25">
                    <button
                      onClick={() => setReaderSize("sm")}
                      className={`px-2 py-1 text-xs font-semibold rounded-lg ${
                        readerSize === "sm" ? "bg-primary text-white" : "hover:bg-current/5"
                      }`}
                    >
                      A-
                    </button>
                    <button
                      onClick={() => setReaderSize("md")}
                      className={`px-2.5 py-1 text-xs font-semibold rounded-lg ${
                        readerSize === "md" ? "bg-primary text-white" : "hover:bg-current/5"
                      }`}
                    >
                      A
                    </button>
                    <button
                      onClick={() => setReaderSize("lg")}
                      className={`px-2 py-1 text-xs font-semibold rounded-lg ${
                        readerSize === "lg" ? "bg-primary text-white" : "hover:bg-current/5"
                      }`}
                    >
                      A+
                    </button>
                  </div>

                  {/* Themes */}
                  <div className="flex items-center gap-1.5">
                    {["sepia", "dark", "light"].map((t) => (
                      <button
                        key={t}
                        onClick={() => setReaderTheme(t as any)}
                        className={`w-6 h-6 rounded-full border text-[10px] font-bold capitalize transition-all hover:scale-105 flex items-center justify-center ${
                          t === "sepia"
                            ? "bg-[#ebdcb9] text-[#433422] border-[#d3c095]"
                            : t === "dark"
                            ? "bg-black text-white border-gray-800"
                            : "bg-white text-black border-gray-300"
                        } ${readerTheme === t ? "ring-2 ring-primary ring-offset-2" : ""}`}
                      >
                        {t[0]}
                      </button>
                    ))}
                  </div>

                  {/* Close button */}
                  <button
                    onClick={() => setReaderOpen(false)}
                    className="p-1.5 rounded-xl hover:bg-current/10 transition-colors"
                  >
                    <X className="h-5 w-5" />
                  </button>
                </div>
              </div>

              {/* Main Area */}
              <div className="flex-1 flex overflow-hidden">
                {/* Sidebar - Table of Contents */}
                <div className={`w-64 border-r hidden md:flex flex-col overflow-y-auto p-4 space-y-2 ${
                  readerTheme === "sepia"
                    ? "border-[#ebdcb9] bg-[#f5ebd6]"
                    : readerTheme === "dark"
                    ? "border-[#2d2d2d] bg-[#161616]"
                    : "border-gray-200 bg-gray-50"
                }`}>
                  <h4 className="font-bold text-xs uppercase tracking-wider opacity-60 mb-2">Table of Contents</h4>
                  {digitalBook.chapters.map((ch: any, idx: number) => (
                    <button
                      key={ch.id}
                      onClick={() => setCurrentChapterIndex(idx)}
                      className={`text-left text-xs p-3 rounded-xl transition-all font-semibold flex flex-col gap-1 border border-transparent ${
                        currentChapterIndex === idx
                          ? "bg-primary text-white border-primary shadow-sm"
                          : "hover:bg-current/5 text-current/80"
                      }`}
                    >
                      <span className="opacity-70 text-[9px] uppercase tracking-wider font-extrabold">Chapter {ch.chapterNumber}</span>
                      <span className="truncate">{ch.title}</span>
                    </button>
                  ))}
                </div>

                {/* Reader Pane */}
                <div className="flex-1 overflow-y-auto px-6 py-8 sm:px-12 flex justify-center">
                  <div className={`max-w-2xl w-full space-y-6 ${
                    readerFont === "serif" ? "font-serif" : "font-sans"
                  } ${
                    readerSize === "sm" ? "text-sm" : readerSize === "lg" ? "text-lg" : "text-base"
                  }`}>
                    {/* Chapter Header */}
                    <div className="border-b pb-4 border-current/10 space-y-1">
                      <span className="text-xs uppercase tracking-wider font-bold opacity-60 font-sans">
                        Chapter {digitalBook.chapters[currentChapterIndex]?.chapterNumber} of {digitalBook.chapters.length}
                      </span>
                      <h1 className="text-2xl sm:text-3xl font-black leading-tight">
                        {digitalBook.chapters[currentChapterIndex]?.title}
                      </h1>
                    </div>

                    {/* Chapter Content */}
                    <div className="leading-relaxed space-y-4 whitespace-pre-line text-current/90 select-text font-medium">
                      {digitalBook.chapters[currentChapterIndex]?.content}
                    </div>
                  </div>
                </div>
              </div>

              {/* Bottom Nav Bar */}
              <div className={`px-6 py-4 border-t flex items-center justify-between ${
                readerTheme === "sepia"
                  ? "border-[#ebdcb9] bg-[#f5ebd6]"
                  : readerTheme === "dark"
                  ? "border-[#2d2d2d] bg-[#161616]"
                  : "border-gray-200 bg-gray-50"
              }`}>
                {/* Chapter Select (Mobile only) */}
                <div className="md:hidden">
                  <select
                    value={currentChapterIndex}
                    onChange={(e) => setCurrentChapterIndex(parseInt(e.target.value))}
                    className="px-2.5 py-1 border rounded-lg bg-transparent text-xs font-semibold focus:outline-none"
                  >
                    {digitalBook.chapters.map((ch: any, idx: number) => (
                      <option key={ch.id} value={idx} className="bg-background text-foreground">
                        Ch {ch.chapterNumber}: {ch.title}
                      </option>
                    ))}
                  </select>
                </div>

                {/* Progress Indicators */}
                <div className="hidden md:flex items-center gap-4 text-xs font-semibold opacity-70">
                  <span>Progress: {Math.round(((currentChapterIndex + 1) / digitalBook.chapters.length) * 100)}%</span>
                  <div className="w-32 h-1.5 bg-current/10 rounded-full overflow-hidden">
                    <div
                      className="bg-primary h-full transition-all duration-300"
                      style={{ width: `${((currentChapterIndex + 1) / digitalBook.chapters.length) * 100}%` }}
                    ></div>
                  </div>
                </div>

                {/* Back / Next Buttons */}
                <div className="flex gap-2">
                  <button
                    onClick={() => setCurrentChapterIndex(Math.max(0, currentChapterIndex - 1))}
                    disabled={currentChapterIndex === 0}
                    className="inline-flex items-center gap-1 border border-current/25 hover:bg-current/5 px-3 py-1.5 rounded-xl text-xs font-bold transition-all disabled:opacity-40"
                  >
                    <ChevronLeft className="h-4 w-4" />
                    <span>Prev</span>
                  </button>
                  <button
                    onClick={() => setCurrentChapterIndex(Math.min(digitalBook.chapters.length - 1, currentChapterIndex + 1))}
                    disabled={currentChapterIndex === digitalBook.chapters.length - 1}
                    className="inline-flex items-center gap-1 border border-current/25 hover:bg-current/5 px-3 py-1.5 rounded-xl text-xs font-bold transition-all disabled:opacity-40"
                  >
                    <span>Next</span>
                    <ChevronRight className="h-4 w-4" />
                  </button>
                </div>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

export default function SearchPage() {
  return (
    <div className="min-h-screen flex flex-col bg-background text-foreground transition-colors duration-200">
      <Navbar />

      <main className="flex-1 mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-10 w-full">
        <Suspense fallback={<p className="text-center font-bold">Loading search results...</p>}>
          <SearchResultsContent />
        </Suspense>
      </main>

      <Footer />
    </div>
  );
}
